CREATE TABLE IF NOT EXISTS components (
	id INT NOT NULL AUTO_INCREMENT UNIQUE,
	type ENUM('text', 'image', 'board', 'note', 'task') NOT NULL,
	owner_id INT NOT NULL,
	width INT NOT NULL,
    height INT NOT NULL,
    component_column INT NOT NULL,
    component_row INT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS task_content (
    id INT NOT NULL UNIQUE,
    task_name VARCHAR(255) NOT NULL,
    start_date DATE,
    end_date DATE,
    completed BOOLEAN,
    repeatable BOOLEAN
);

CREATE TABLE IF NOT EXISTS text_content (
	id INT NOT NULL PRIMARY KEY,
    content TEXT
);


CREATE TABLE IF NOT EXISTS image_content (
	id INT NOT NULL PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS note_content (
    id INT NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS labels (
    label_name VARCHAR(255) NOT NULL PRIMARY KEY,
    color VARCHAR(7)
);


CREATE TABLE IF NOT EXISTS label_component (
    label_name VARCHAR(255) NOT NULL,
    component_id INT NOT NULL,
    PRIMARY KEY (label_name, component_id)
);


CREATE TABLE IF NOT EXISTS board_content (
	id INT NOT NULL PRIMARY KEY,
	board_name VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS container_children (
	id_child INT NOT NULL,
	id_container INT NOT NULL
);


CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT UNIQUE,
	username VARCHAR(31) NOT NULL UNIQUE,
	display_name VARCHAR(255),
	email VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(4095),
	avatar VARCHAR(255),
	avatar_type ENUM('jpg', 'png', 'gif'),
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS groups (
	id INT NOT NULL AUTO_INCREMENT UNIQUE,
	owner_id INT NOT NULL,
	name VARCHAR(255),
	is_friendlist BOOLEAN NOT NULL,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS group_members (
	member_id INT NOT NULL,
	group_id INT NOT NULL
);


CREATE TABLE IF NOT EXISTS permissions (
	component_id INT NOT NULL,
	group_id INT NOT NULL,
	read BOOLEAN,
	write BOOLEAN
);


CREATE TABLE IF NOT EXISTS passwords (
	user_id INT NOT NULL UNIQUE,
	hash VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS salts (
	user_id INT NOT NULL UNIQUE,
	salt VARCHAR(255) NOT NULL
);

ALTER TABLE task_content
ADD FOREIGN KEY(id) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE text_content
ADD FOREIGN KEY(id) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE image_content
ADD FOREIGN KEY(id) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE board_content
ADD FOREIGN KEY(id) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE note_content
ADD FOREIGN KEY(id) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE container_children
ADD FOREIGN KEY(id_child) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE container_children
ADD FOREIGN KEY(id_container) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE label_component
ADD FOREIGN KEY(label_name) REFERENCES labels(label_name)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE label_component
ADD FOREIGN KEY(component_id) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE components
ADD FOREIGN KEY(owner_id) REFERENCES users(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE group_members
ADD FOREIGN KEY(group_id) REFERENCES groups(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE groups
ADD FOREIGN KEY(owner_id) REFERENCES users(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE group_members
ADD FOREIGN KEY(member_id) REFERENCES users(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE permissions
ADD FOREIGN KEY(component_id) REFERENCES components(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE permissions
ADD FOREIGN KEY(group_id) REFERENCES groups(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE passwords
ADD FOREIGN KEY(user_id) REFERENCES users(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE salts
ADD FOREIGN KEY(user_id) REFERENCES users(id)
ON UPDATE NO ACTION ON DELETE CASCADE;